USE Tours;
GO

CREATE TABLE Bookings (
    Id VARCHAR(36) PRIMARY KEY,
    UserId VARCHAR(36) NOT NULL,
    ToursId UNIQUEIDENTIFIER,
    HotelsId UNIQUEIDENTIFIER,
    BookingDate DATE NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(id),
    FOREIGN KEY (ToursId) REFERENCES Tours(id),
    FOREIGN KEY (HotelsId) REFERENCES Hotels(id)
);

